### ISSUE TITLE
Лор

### ISSUE THREAD

**Issue by Qwebeck** [aI-lab-glider/helgry-space#1]
Ціль завдання - описати світ в якому відбуваються події нашої гри. 
На початковому рівні - це щось, що складається з:
- картинки головного героя,
- нарис пейзажів (тобто або гарне фото з фільму, книги, коміксу, або власний малюнок в Paint/Figma/Photoshop) ,
- короткої передісторії,
- ясно визначеної цілі героя, яка пояснює чому він виконує те що виконує.

**Comment by Olexandrprograming** [comment]
Суть сюжету полягає у тому що головний герой був астрономом який досліджував зорі і одного дня він побачив дивний літаючий об'єкт у небі. Це були інопланетяни які хотіли знищити Землю, не знаючи, що люди не настільки розвинені, вони подумали, що гг зараз за допомогою телепатії повідомить про небезпеку і їм буде непереливки, тому вони вирішили захопити єдиного свідка і втекти.
 На своїй планеті інопланетяни перетворили гг в піддослідного кролика і ставили над ним експерименти  внаслідок чого він отримав можливість супер стрибка, зрозумівши що ціль експерименту недосягнута вони просто залишили його на третій планеті помирати, але гг одного дня під час експерименту почув, що через деякий час вони збирають повернутися на Землю, щоб досягти цілі експериментів яка йому не відома, тому вирішив завадити їм це зробити і використовуючи свою можливість супер стрибка почав свою подорож всесвітом.
